# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
user = User.create(email: 'test@email.com', username: 'user', password: 'password', password_confirmation: 'password')
user.create_player(name: 'player')

Skill.create(name: "Astrogation", attrib: "Intellect")
Skill.create(name: "Athletics", attrib: "Brawn")
Skill.create(name: "Charm", attrib: "Presence")
Skill.create(name: "Coerce", attrib: "Willpower")
Skill.create(name: "Computers", attrib: "Intellect")
Skill.create(name: "Cool", attrib: "Presence")
Skill.create(name: "Coordination", attrib: "Agility")
Skill.create(name: "Deceit", attrib: "Cunning")
Skill.create(name: "Discipline", attrib: "Willpower")
Skill.create(name: "Knowledge - Core Worlds", attrib: "Intellect")
Skill.create(name: "Knowledge - Education", attrib: "Intellect")
Skill.create(name: "Knowledge - Lore", attrib: "Intellect")
Skill.create(name: "Knowledge - Outer Rim", attrib: "Intellect")
Skill.create(name: "Knowledge - Xenology", attrib: "Intellect")
Skill.create(name: "Knowledge - Underworld", attrib: "Intellect")
Skill.create(name: "Leadership", attrib: "Presence")
Skill.create(name: "Mechanics", attrib: "Intellect")
Skill.create(name: "Medicine", attrib: "Intellect")
Skill.create(name: "Negotiation", attrib: "Presence")
Skill.create(name: "Perception", attrib: "Cunning")
Skill.create(name: "Pilot - Planet", attrib: "Agility")
Skill.create(name: "Pilot - Space", attrib: "Agility")
Skill.create(name: "Resilience", attrib: "Brawn")
Skill.create(name: "Skulduggery", attrib: "Cunning")
Skill.create(name: "Stealth", attrib: "Agility")
Skill.create(name: "Streetwise", attrib: "Cunning")
Skill.create(name: "Survival", attrib: "Cunning")
Skill.create(name: "Surveillance", attrib: "Cunning")
Skill.create(name: "Vigilance", attrib: "Willpower")

Skill.create(name: "Brawl", attrib: "Brawn")
Skill.create(name: "Gunnery", attrib: "Agility")
Skill.create(name: "Melee", attrib: "Brawn")
Skill.create(name: "Ranged - Light", attrib: "Agility")
Skill.create(name: "Ranged - Heavy", attrib: "Agility")

Race.create(name: "Bothan", agility: 2, brawn: 1, intellect: 2, presence: 2, willpower: 2, cunning: 3, wounds_thresh: 10, strain_thresh: 11, xp: 100, bonus: "Streetwise")
Race.create(name: "Droid", agility: 1, brawn: 1, intellect: 1, presence: 1, willpower: 1, cunning: 1, wounds_thresh: 10, strain_thresh: 10, xp: 175, bonus: "None")
Race.create(name: "Gand", agility: 2, brawn: 2, intellect: 1, presence: 2, willpower: 3, cunning: 2, wounds_thresh: 10, strain_thresh: 10, xp: 100, bonus: "Discipline")
Race.create(name: "Human", agility: 2, brawn: 2, intellect: 2, presence: 2, willpower: 2, cunning: 2, wounds_thresh: 10, strain_thresh: 10, xp: 110, bonus: "Specialty")
Race.create(name: "Rodian", agility: 3, brawn: 2, intellect: 2, presence: 2, willpower: 1, cunning: 2, wounds_thresh: 10, strain_thresh: 10, xp: 100, bonus: "Survival")
Race.create(name: "Trandoshan", agility: 1, brawn: 3, intellect: 2, presence: 2, willpower: 2, cunning: 2, wounds_thresh: 12, strain_thresh: 9, xp: 90, bonus: "Perception")
Race.create(name: "Twi'lek", agility: 2, brawn: 1, intellect: 2, presence: 3, willpower: 2, cunning: 2, wounds_thresh: 10, strain_thresh: 11, xp: 100, bonus: "Charm-Deceit")
Race.create(name: "Wookiee", agility: 2, brawn: 3, intellect: 2, presence: 2, willpower: 1, cunning: 2, wounds_thresh: 14, strain_thresh: 8, xp: 90, bonus: "Brawl")


c1 = Career.create(name: "Bounty Hunter")
c1.skills << Skill.find_by_name("Athletics")
c1.skills << Skill.find_by_name("Perception")
c1.skills << Skill.find_by_name("Pilot - Planet")
c1.skills << Skill.find_by_name("Pilot - Space")
c1.skills << Skill.find_by_name("Streetwise")
c1.skills << Skill.find_by_name("Surveillance")
c1.skills << Skill.find_by_name("Vigilance")
c1.skills << Skill.find_by_name("Ranged - Heavy")

c1 = Career.create(name: "Colonist")
c1.skills << Skill.find_by_name("Charm")
c1.skills << Skill.find_by_name("Deceit")
c1.skills << Skill.find_by_name("Leadership")
c1.skills << Skill.find_by_name("Negotiation")
c1.skills << Skill.find_by_name("Streetwise")
c1.skills << Skill.find_by_name("Knowledge - Core Worlds")
c1.skills << Skill.find_by_name("Knowledge - Education")
c1.skills << Skill.find_by_name("Knowledge - Lore")

c1 = Career.create(name: "Explorer")
c1.skills << Skill.find_by_name("Astrogation")
c1.skills << Skill.find_by_name("Charm")
c1.skills << Skill.find_by_name("Cool")
c1.skills << Skill.find_by_name("Perception")
c1.skills << Skill.find_by_name("Pilot - Space")
c1.skills << Skill.find_by_name("Knowledge - Lore")
c1.skills << Skill.find_by_name("Knowledge - Outer Rim")
c1.skills << Skill.find_by_name("Knowledge - Xenology")

c1 = Career.create(name: "Hired Gun")
c1.skills << Skill.find_by_name("Athletics")
c1.skills << Skill.find_by_name("Discipline")
c1.skills << Skill.find_by_name("Pilot - Planet")
c1.skills << Skill.find_by_name("Resilience")
c1.skills << Skill.find_by_name("Vigilance")
c1.skills << Skill.find_by_name("Brawl")
c1.skills << Skill.find_by_name("Melee")
c1.skills << Skill.find_by_name("Ranged - Light")

c1 = Career.create(name: "Smuggler")
c1.skills << Skill.find_by_name("Coordination")
c1.skills << Skill.find_by_name("Deceit")
c1.skills << Skill.find_by_name("Perception")
c1.skills << Skill.find_by_name("Pilot - Space")
c1.skills << Skill.find_by_name("Skulduggery")
c1.skills << Skill.find_by_name("Streetwise")
c1.skills << Skill.find_by_name("Vigilance")
c1.skills << Skill.find_by_name("Knowledge - Underworld")

c1 = Career.create(name: "Technician")
c1.skills << Skill.find_by_name("Astrogation")
c1.skills << Skill.find_by_name("Computers")
c1.skills << Skill.find_by_name("Coordination")
c1.skills << Skill.find_by_name("Discipline")
c1.skills << Skill.find_by_name("Mechanics")
c1.skills << Skill.find_by_name("Perception")
c1.skills << Skill.find_by_name("Pilot - Planet")
c1.skills << Skill.find_by_name("Surveillance")